version: "3.7"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile-tests
    links:
      - splunk
    volumes:
      - results:/work/test-results

  splunk:
    build:
      context: .
      dockerfile: Dockerfile-splunk
      args:
        - SPLUNK_APP=Splunk_TA_symantec-ep
        - SPLUNK_VERSION=${SPLUNK_VERSION}
    hostname: splunk
    ports:
      - "8000"
      - "8088"
      - "8089"
      - "9997"
    environment:
      - SPLUNK_PASSWORD=Chang3d!
      - SPLUNK_START_ARGS=--accept-license

volumes:
  results:
    external: false