dependencies:
  cache_directories:
    - "~/.apt-cache"
  pre:
    - sudo rm -rf /var/cache/apt/archives && sudo ln -s ~/.apt-cache /var/cache/apt/archives && mkdir -p ~/.apt-cache/partial

apt-run: &apt-install
  name: install system packages
  command: |
    sudo apt update -qq
    sudo apt install -y python-pip

version: 2.1
jobs:
  splunk-app-package:
      docker:
        - image: circleci/python:2.7
      steps:
        - checkout
        - run:
            name: Install SLIM
            command: |
              pip install virtualenv
              mkdir ~/.venv
              virtualenv ~/.venv
              source ~/.venv/bin/activate
              pip install semantic_version
              pip install https://download.splunk.com/misc/packaging-toolkit/splunk-packaging-toolkit-1.0.0.tar.gz
              pip install git+https://github.com/pixelb/crudini
        - run:
            name: Check version
            command: |
              source ~/.venv/bin/activate   
              mkdir -p build
              VERSION=$(crudini --get package/default/app.conf id version)
              PACKAGE_ID=$(crudini --get package/default/app.conf id name)
        - run:
            name: Package app
            command: |
              source ~/.venv/bin/activate                
              BUILD_DIR=build/source/$PACKAGE_ID
              mkdir -p $BUILD_DIR
              cp -r package/* $BUILD_DIR/
              slim generate-manifest $BUILD_DIR --update >/tmp/app.manifest   || true
              cp  /tmp/app.manifest  $BUILD_DIR/app.manifest
              mkdir -p build/package/splunkbase
              mkdir -p build/package/deployment
              slim package -o build/package/splunkbase $BUILD_DIR 
              ls build/package/splunkbase

  splunk-app-inspect:
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          name: Install Splunk AppInspect
          command: |
            python -m venv ~/.venv
            source ~/.venv/bin/activate
            pip install https://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz
      - run:
          name: Inspect app (Badge)
          command: |
            source ~/.venv/bin/activate
            mkdir test-results || true
            PACKAGE=$(ls /tmp/workspace/build/package/splunkbase/*)
            splunk-appinspect inspect --mode test --data-format junitxml --output-file test-results/appinspect-mode-badge.xml $PACKAGE
            if grep failures=\"[1-9] test-results/appinspect-mode-badge.xml; then exit 1; else exit 0; fi
      - run:
          name: Inspect app (Cloud)
          command: |
            source ~/.venv/bin/activate
            mkdir test-results || true
            PACKAGE=$(ls /tmp/workspace/build/package/splunkbase/*)
            splunk-appinspect inspect --mode precert --included-tags cloud --data-format junitxml --output-file test-results/appinspect-mode-cloud.xml $PACKAGE
            if grep failures=\"[1-9] test-results/appinspect-mode-cloud.xml; then exit 1; else exit 0; fi

workflows:
  build:
    jobs:
      - splunk-app-package:
          filters:
            branches:
              only: /.*/
      - splunk-app-inspect:
          filters:
            branches:
              only: /.*/