version: 2
orbs:
  splunk-app-package:
    executors:
      python27:
        docker:
          - image: circleci/python:2.7
    commands:
      package:
        steps:
          - run:
              name: Install SLIM
              command: |
                pip install virtualenv
                mkdir ~/.venv
                virtualenv ~/.venv
                source ~/.venv/bin/activate
                pip install semantic_version
                pip install https://download.splunk.com/misc/packaging-toolkit/splunk-packaging-toolkit-1.0.0.tar.gz
                pip install git+https://github.com/pixelb/crudini
          - run:
              name: Check version
              command: |
                source ~/.venv/bin/activate   
                mkdir -p build

          - run:
              name: Package app
              command: |
                source build/VERSION
                source ~/.venv/bin/activate                
                BUILD_DIR=build/source/$PACKAGE_ID
                mkdir -p $BUILD_DIR
                cp -r src/${CIRCLE_PROJECT_REPONAME}/* $BUILD_DIR/
                crudini --set $BUILD_DIR/default/app.conf launcher version $VERSION_SPLUNK
                crudini --set $BUILD_DIR/default/app.conf id version $VERSION_SPLUNK
                crudini --set $BUILD_DIR/default/app.conf install build ${PACKAGE_BUILD}
                slim generate-manifest $BUILD_DIR --update >/tmp/app.manifest   || true
                cp  /tmp/app.manifest  $BUILD_DIR/app.manifest
                mkdir -p build/package/splunkbase
                mkdir -p build/package/deployment
                slim package -o build/package/splunkbase $BUILD_DIR 
                ls build/package/splunkbase

  splunk-app-inspect:
    executors:
      python37:
        docker:
          - image: circleci/python:3.7
    commands:
      inspect:
        parameters:
          options:
            description: Inspect options
            type: string
            default: --mode test
          label:
            description: string to identify test options in file name of output
            type: string
            default: test
        steps:
          - run:
              name: Install Splunk AppInspect
              command: |
                python -m venv ~/.venv
                source ~/.venv/bin/activate
                pip install https://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz
          - run:
              name: Inspect app
              command: |
                source ~/.venv/bin/activate
                mkdir test-results || true
                PACKAGE=$(ls /tmp/workspace/build/package/splunkbase/*)
                splunk-appinspect inspect <<parameters.options>> --data-format junitxml --output-file test-results/appinspect-mode-<<parameters.label>>.xml $PACKAGE
                if grep failures=\"[1-9] test-results/appinspect-mode-<<parameters.label>>.xml; then exit 1; else exit 0; fi

jobs:
  publish-gh:
    docker:
      - image: circleci/python:3.7
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - go/install
      - run:
          name: "Publish on GitHub"
          command: |
            PATH=$PATH:/usr/local/go/bin
            PACKAGE=$(ls /tmp/workspace/build/package/splunkbase/*)
            source /tmp/workspace/build/VERSION
            go get -v -u github.com/tcnksm/ghr            
            $HOME/go/bin/ghr -t ${GH_PAT} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${ISPRE} -delete ${VERSION} $PACKAGE

workflows:
  version: 2
  build:
    jobs:
      - splunk-app-package/package:
          name: package
          filters:
            branches:
              only: /.*/
      - splunk-app-inspect/inspect:
          name: splunk-app-inspect-badge
          options: "--mode test"
          label: "badge"
          filters:
            branches:
              only: /.*/
          requires:
            - package
      - splunk-app-inspect/inspect:
          name: splunk-app-inspect-cloud
          options: "--mode precert --included-tags cloud"
          label: "cloud"
          filters:
            branches:
              only: /.*/
          requires:
            - package